"""Markdown shortlist formatter."""

from typing import List
from agent.models import Listing, SearchQuery


def to_markdown(listings: List[Listing], query: SearchQuery) -> str:
    lines = []
    lines.append("# Internship shortlist")
    lines.append("")
    kw = ", ".join(query.keywords) if query.keywords else "(any)"
    lines.append(f"**Keywords:** {kw}  ")
    lines.append(f"**Location preference:** {query.location or 'any'}  ")
    lines.append(f"**Remote OK:** {query.remote_ok}  ")
    lines.append(f"**Results:** {len(listings)}")
    lines.append("")

    if not listings:
        lines.append("_No matching listings found._")
        return "\n".join(lines)

    for i, job in enumerate(listings, 1):
        lines.append(f"## {i}. {job.title}")
        lines.append(f"- **Company:** {job.company}")
        lines.append(f"- **Location:** {job.location}")
        lines.append(f"- **Source:** {job.source}")
        if job.posted_at:
            lines.append(f"- **Posted:** {job.posted_at}")
        lines.append(f"- **Score:** {job.score:.1f}")
        lines.append(f"- **Link:** {job.url}")
        if job.description:
            snippet = job.description.replace("\n", " ").strip()
            if len(snippet) > 220:
                snippet = snippet[:217] + "..."
            lines.append(f"- **Summary:** {snippet}")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by AI Internship Agent. Verify each posting before applying._")
    return "\n".join(lines)
